// ============================================================
// CTP hole resolution — pinned to the Dart resolver
// ============================================================
// W4b. `__fixtures__/ctp-holes.json` is GENERATED by the Flutter
// repo's test/parity/ctp_holes_fixtures_test.dart, which runs the
// real `resolveCtpHolesFor`. This replays every case through the
// TypeScript port.
//
// When this fails the TypeScript is wrong until proven otherwise:
// the app's resolver is what decides whether a CTP prize exists.

import { describe, expect, it } from 'vitest';

import {
  anyRoundTracksCtp,
  explicitCtpHoles,
  longestDriveGenders,
  par3Holes,
  resolveCtpHoles,
} from './ctpHoles';
import fixtures from './__fixtures__/ctp-holes.json';
import type { TournamentRound, TournamentRow } from './tournamentQueries';

type Case = {
  label: string;
  ctpHoles: number[] | null;
  trackCTPOnPar3s: boolean;
  roundPars: number[] | null;
  tournamentPars: number[] | null;
  expectedCtpHoles: number[];
  expectedPar3Holes: number[];
  expectedAnyRoundTracksCtp: boolean;
};

const cases = fixtures.cases as Case[];

const tee = (pars: number[] | null) => ({
  teeName: 'Blue',
  pars: pars ?? undefined,
  parTotal: 72,
  slopeRating: 113,
  courseRating: 72,
});

function build(c: Case): { t: TournamentRow; r: TournamentRound } {
  const r = {
    id: 'r1',
    name: 'R1',
    format: 'stroke_play',
    tee_boxes: c.roundPars === null ? [] : [tee(c.roundPars)],
    // Absent vs empty is the distinction under test, so only set the
    // key when the fixture says the list is explicit.
    ...(c.ctpHoles === null ? {} : { ctp_holes: c.ctpHoles }),
  } as unknown as TournamentRound;
  const t = {
    id: 't1',
    user_id: 'u1',
    name: 'T',
    course_name: null,
    total_holes: 18,
    par_total: 72,
    created_at: null,
    updated_at: null,
    completed_at: null,
    players: [],
    tee_boxes: c.tournamentPars === null ? [] : [tee(c.tournamentPars)],
    rounds: [r],
    track_ctp_on_par_3s: c.trackCTPOnPar3s,
  } as unknown as TournamentRow;
  return { t, r };
}

describe('resolveCtpHoles matches the Dart resolver', () => {
  for (const c of cases) {
    it(c.label, () => {
      const { t, r } = build(c);
      expect(resolveCtpHoles(t, r)).toEqual(c.expectedCtpHoles);
      expect(par3Holes(t, r)).toEqual(c.expectedPar3Holes);
      expect(anyRoundTracksCtp(t)).toBe(c.expectedAnyRoundTracksCtp);
    });
  }
});

describe('the fixture still covers what it was built for', () => {
  it('has cases at all', () => {
    expect(cases.length).toBeGreaterThanOrEqual(8);
  });

  it('distinguishes explicit-empty from absent', () => {
    // The distinction a TypeScript port most easily loses.
    const empty = cases.find((c) => Array.isArray(c.ctpHoles) && c.ctpHoles.length === 0);
    const absent = cases.find((c) => c.ctpHoles === null && c.trackCTPOnPar3s);
    expect(empty).toBeTruthy();
    expect(absent).toBeTruthy();
    // And they must disagree, or the case pair proves nothing.
    expect(empty!.expectedCtpHoles).toEqual([]);
    expect(absent!.expectedCtpHoles.length).toBeGreaterThan(0);
  });

  it('covers an explicit hole that is NOT a par 3', () => {
    // A port that intersected the explicit list with the par 3s would
    // pass every other case and fail only this one.
    const odd = cases.find((c) =>
      Array.isArray(c.ctpHoles)
      && c.ctpHoles.length > 0
      && c.ctpHoles.some((h) => !c.expectedPar3Holes.includes(h)));
    expect(odd).toBeTruthy();
  });

  it('covers a round whose pars differ from the tournament pars', () => {
    const divergent = cases.find((c) =>
      c.roundPars && c.tournamentPars
      && JSON.stringify(c.roundPars) !== JSON.stringify(c.tournamentPars));
    expect(divergent).toBeTruthy();
  });
});

describe('explicitCtpHoles', () => {
  const asRound = (o: Record<string, unknown>) => o as unknown as TournamentRound;

  it('separates absent from empty', () => {
    expect(explicitCtpHoles(asRound({}))).toBeNull();
    expect(explicitCtpHoles(asRound({ ctp_holes: [] }))).toEqual([]);
  });

  it('reads both wire spellings', () => {
    expect(explicitCtpHoles(asRound({ ctpHoles: [5] }))).toEqual([5]);
    expect(explicitCtpHoles(asRound({ ctp_holes: [5] }))).toEqual([5]);
  });

  it('treats junk as absent rather than as "no CTP"', () => {
    // Falling back is the safe direction: a malformed row should not
    // silently disable a prize the director configured.
    expect(explicitCtpHoles(asRound({ ctp_holes: 'nope' }))).toBeNull();
    expect(explicitCtpHoles(asRound({ ctp_holes: null }))).toBeNull();
  });

  it('drops non-numeric and out-of-range entries', () => {
    expect(explicitCtpHoles(asRound({ ctp_holes: [1, 'x', 0, -3, 7] })))
      .toEqual([1, 7]);
  });
});

describe('longestDriveGenders', () => {
  const t = (o: Record<string, unknown>) => o as unknown as TournamentRow;

  it('is empty when longest drive is off', () => {
    expect(longestDriveGenders(t({}))).toEqual([]);
    expect(longestDriveGenders(t({ track_longest_drive: false }))).toEqual([]);
  });

  it('shows BOTH brackets for a legacy tournament with no picker data', () => {
    // Documented legacy behaviour: the app's settlement screen renders
    // both rows when the genders list predates the picker.
    expect(longestDriveGenders(t({ track_longest_drive: true })))
      .toEqual(['male', 'female']);
    expect(longestDriveGenders(t({
      track_longest_drive: true,
      longest_drive_genders: [],
    }))).toEqual(['male', 'female']);
  });

  it('honours an explicit pick', () => {
    expect(longestDriveGenders(t({
      track_longest_drive: true,
      longest_drive_genders: ['female'],
    }))).toEqual(['female']);
  });

  it('normalises case and ignores unknown values', () => {
    expect(longestDriveGenders(t({
      track_longest_drive: true,
      longest_drive_genders: ['MALE', ' female ', 'other'],
    }))).toEqual(['male', 'female']);
    // All-unknown falls back rather than hiding LD entirely.
    expect(longestDriveGenders(t({
      track_longest_drive: true,
      longest_drive_genders: ['other'],
    }))).toEqual(['male', 'female']);
  });
});
