// ============================================================
// CTP hole resolution — pinned to the Dart resolver
// ============================================================
// W4b. `__fixtures__/ctp-holes.json` is GENERATED by the Flutter
// repo's test/parity/ctp_holes_fixtures_test.dart, which runs the
// real `resolveCtpHolesFor`. This replays every case through the
// TypeScript port.
//
// When this fails the TypeScript is wrong until proven otherwise:
// the app's resolver is what decides whether a CTP prize exists.

import { describe, expect, it } from 'vitest';

import {
  anyRoundTracksCtp,
  explicitCtpHoles,
  longestDriveGenders,
  mergeCtpWinners,
  par3Holes,
  resolveCtpHoles,
} from './ctpHoles';
import fixtures from './__fixtures__/ctp-holes.json';
import type { TournamentRound, TournamentRow } from './tournamentQueries';

type Case = {
  label: string;
  ctpHoles: number[] | null;
  trackCTPOnPar3s: boolean;
  roundPars: number[] | null;
  tournamentPars: number[] | null;
  expectedCtpHoles: number[];
  expectedPar3Holes: number[];
  expectedAnyRoundTracksCtp: boolean;
};

const cases = fixtures.cases as Case[];

const tee = (pars: number[] | null) => ({
  teeName: 'Blue',
  pars: pars ?? undefined,
  parTotal: 72,
  slopeRating: 113,
  courseRating: 72,
});

function build(c: Case): { t: TournamentRow; r: TournamentRound } {
  const r = {
    id: 'r1',
    name: 'R1',
    format: 'stroke_play',
    tee_boxes: c.roundPars === null ? [] : [tee(c.roundPars)],
    // Absent vs empty is the distinction under test, so only set the
    // key when the fixture says the list is explicit.
    ...(c.ctpHoles === null ? {} : { ctp_holes: c.ctpHoles }),
  } as unknown as TournamentRound;
  const t = {
    id: 't1',
    user_id: 'u1',
    name: 'T',
    course_name: null,
    total_holes: 18,
    par_total: 72,
    created_at: null,
    updated_at: null,
    completed_at: null,
    players: [],
    tee_boxes: c.tournamentPars === null ? [] : [tee(c.tournamentPars)],
    rounds: [r],
    track_ctp_on_par_3s: c.trackCTPOnPar3s,
  } as unknown as TournamentRow;
  return { t, r };
}

describe('resolveCtpHoles matches the Dart resolver', () => {
  for (const c of cases) {
    it(c.label, () => {
      const { t, r } = build(c);
      expect(resolveCtpHoles(t, r)).toEqual(c.expectedCtpHoles);
      expect(par3Holes(t, r)).toEqual(c.expectedPar3Holes);
      expect(anyRoundTracksCtp(t)).toBe(c.expectedAnyRoundTracksCtp);
    });
  }
});

describe('the fixture still covers what it was built for', () => {
  it('has cases at all', () => {
    expect(cases.length).toBeGreaterThanOrEqual(8);
  });

  it('distinguishes explicit-empty from absent', () => {
    // The distinction a TypeScript port most easily loses.
    const empty = cases.find((c) => Array.isArray(c.ctpHoles) && c.ctpHoles.length === 0);
    const absent = cases.find((c) => c.ctpHoles === null && c.trackCTPOnPar3s);
    expect(empty).toBeTruthy();
    expect(absent).toBeTruthy();
    // And they must disagree, or the case pair proves nothing.
    expect(empty!.expectedCtpHoles).toEqual([]);
    expect(absent!.expectedCtpHoles.length).toBeGreaterThan(0);
  });

  it('covers an explicit hole that is NOT a par 3', () => {
    // A port that intersected the explicit list with the par 3s would
    // pass every other case and fail only this one.
    const odd = cases.find((c) =>
      Array.isArray(c.ctpHoles)
      && c.ctpHoles.length > 0
      && c.ctpHoles.some((h) => !c.expectedPar3Holes.includes(h)));
    expect(odd).toBeTruthy();
  });

  it('covers a round whose pars differ from the tournament pars', () => {
    const divergent = cases.find((c) =>
      c.roundPars && c.tournamentPars
      && JSON.stringify(c.roundPars) !== JSON.stringify(c.tournamentPars));
    expect(divergent).toBeTruthy();
  });
});

describe('explicitCtpHoles', () => {
  const asRound = (o: Record<string, unknown>) => o as unknown as TournamentRound;

  it('separates absent from empty', () => {
    expect(explicitCtpHoles(asRound({}))).toBeNull();
    expect(explicitCtpHoles(asRound({ ctp_holes: [] }))).toEqual([]);
  });

  it('reads both wire spellings', () => {
    expect(explicitCtpHoles(asRound({ ctpHoles: [5] }))).toEqual([5]);
    expect(explicitCtpHoles(asRound({ ctp_holes: [5] }))).toEqual([5]);
  });

  it('treats junk as absent rather than as "no CTP"', () => {
    // Falling back is the safe direction: a malformed row should not
    // silently disable a prize the director configured.
    expect(explicitCtpHoles(asRound({ ctp_holes: 'nope' }))).toBeNull();
    expect(explicitCtpHoles(asRound({ ctp_holes: null }))).toBeNull();
  });

  it('drops non-numeric and out-of-range entries', () => {
    expect(explicitCtpHoles(asRound({ ctp_holes: [1, 'x', 0, -3, 7] })))
      .toEqual([1, 7]);
  });
});

describe('longestDriveGenders', () => {
  const t = (o: Record<string, unknown>) => o as unknown as TournamentRow;
  const on = (o: Record<string, unknown> = {}) =>
    t({ track_longest_drive: true, ...o });

  it('is empty when longest drive is off', () => {
    expect(longestDriveGenders(t({}))).toEqual([]);
    expect(longestDriveGenders(t({ track_longest_drive: false }))).toEqual([]);
  });

  it('REGRESSION: an ABSENT field_gender means a MEN\'S event', () => {
    // `Tournament.toApiJson` omits the key when it is 'male', because
    // male is the model default. Reading absent as "mixed" rendered a
    // Women's picker on every men's tournament — which is what this
    // code did before, and would have let a director record a winner
    // in a bracket the event does not have.
    expect(longestDriveGenders(on())).toEqual(['male']);
  });

  it('REGRESSION: a women\'s event offers only the women\'s bracket', () => {
    expect(longestDriveGenders(on({ field_gender: 'female' }))).toEqual(['female']);
  });

  it('a men\'s event stated explicitly is the same as absent', () => {
    expect(longestDriveGenders(on({ field_gender: 'male' }))).toEqual(['male']);
  });

  it('a single-gender event IGNORES longest_drive_genders', () => {
    // The wizard only persists that list for mixed events, so a stale
    // value on a single-gender event must not win over field_gender.
    expect(longestDriveGenders(on({
      field_gender: 'female',
      longest_drive_genders: ['male'],
    }))).toEqual(['female']);
  });

  it('mixed + explicit pick honours the pick', () => {
    expect(longestDriveGenders(on({
      field_gender: 'mixed',
      longest_drive_genders: ['female'],
    }))).toEqual(['female']);
  });

  it('mixed + no pick shows BOTH — documented legacy behaviour', () => {
    expect(longestDriveGenders(on({ field_gender: 'mixed' })))
      .toEqual(['male', 'female']);
    expect(longestDriveGenders(on({
      field_gender: 'mixed',
      longest_drive_genders: [],
    }))).toEqual(['male', 'female']);
  });

  it('normalises case, dedupes, and ignores unknown values', () => {
    expect(longestDriveGenders(on({
      field_gender: 'MIXED',
      longest_drive_genders: ['MALE', ' female ', 'male', 'other'],
    }))).toEqual(['male', 'female']);
    // All-unknown on a mixed event falls back rather than hiding LD.
    expect(longestDriveGenders(on({
      field_gender: 'mixed',
      longest_drive_genders: ['other'],
    }))).toEqual(['male', 'female']);
  });

  it('reads the camelCase wire spelling too', () => {
    expect(longestDriveGenders(t({
      trackLongestDrive: true,
      fieldGender: 'female',
    }))).toEqual(['female']);
  });
});

describe('mergeCtpWinners — must MERGE, never replace', () => {
  // THE REGRESSION THIS FILE EXISTS FOR.
  //
  // The editor renders pickers only for holes the round currently
  // tracks. Building the stored map from just those pickers silently
  // deletes a winner on any hole no longer tracked — the exact drop
  // the app's `_mergeClosestToPin` was written to survive.
  const opts = (tracked: number[], roster: string[]) => ({
    tracked: new Set(tracked),
    roster: new Set(roster),
  });

  it('keeps a winner on a hole that is no longer tracked', () => {
    // Holes 5 and 15 were CTP when the winners were recorded; the
    // director has since changed the round to hole 11 only.
    const { winners, rejected } = mergeCtpWinners(
      { '5': 'p1', '15': 'p2' },
      { '11': 'p3' },
      opts([11], ['p1', 'p2', 'p3']),
    );
    expect(winners).toEqual({ '5': 'p1', '15': 'p2', '11': 'p3' });
    expect(rejected).toEqual([]);
  });

  it('changes nothing when the client posts no CTP at all', () => {
    // Saving only a longest-drive winner must not touch CTP. Before
    // the fix this wiped every recorded winner.
    const { winners } = mergeCtpWinners(
      { '5': 'p1', '15': 'p2' },
      {},
      opts([5, 15], ['p1', 'p2']),
    );
    expect(winners).toEqual({ '5': 'p1', '15': 'p2' });
  });

  it('an explicit blank CLEARS that hole and only that hole', () => {
    const { winners } = mergeCtpWinners(
      { '5': 'p1', '15': 'p2' },
      { '5': '' },
      opts([5, 15], ['p1', 'p2']),
    );
    expect(winners).toEqual({ '15': 'p2' });
  });

  it('treats whitespace-only and null as a blank', () => {
    const { winners } = mergeCtpWinners(
      { '5': 'p1', '7': 'p2' },
      { '5': '   ', '7': null },
      opts([5, 7], ['p1', 'p2']),
    );
    expect(winners).toEqual({});
  });

  it('overwrites a winner on a tracked hole', () => {
    const { winners } = mergeCtpWinners(
      { '5': 'p1' }, { '5': 'p2' }, opts([5], ['p1', 'p2']),
    );
    expect(winners).toEqual({ '5': 'p2' });
  });

  it('rejects a winner on an untracked hole without touching the map', () => {
    const { winners, rejected } = mergeCtpWinners(
      { '5': 'p1' }, { '9': 'p2' }, opts([5], ['p1', 'p2']),
    );
    expect(rejected).toHaveLength(1);
    expect(rejected[0]).toMatch(/hole 9/);
    expect(winners).toEqual({ '5': 'p1' });
  });

  it('rejects a winner who is not on the roster', () => {
    const { rejected } = mergeCtpWinners(
      {}, { '5': 'ghost' }, opts([5], ['p1']),
    );
    expect(rejected).toHaveLength(1);
    expect(rejected[0]).toMatch(/roster/);
  });

  it('CAN still clear an untracked hole', () => {
    // Clearing is how a director removes a now-irrelevant winner, so
    // the tracked-hole check must not block a blank.
    const { winners, rejected } = mergeCtpWinners(
      { '5': 'p1' }, { '5': '' }, opts([11], ['p1']),
    );
    expect(winners).toEqual({});
    expect(rejected).toEqual([]);
  });

  it('normalises stored keys and drops junk from the stored map', () => {
    const { winners } = mergeCtpWinners(
      { '05': 'p1', abc: 'p2', '0': 'p3', '-1': 'p4', '7': '' },
      {},
      opts([5], ['p1', 'p2', 'p3', 'p4']),
    );
    expect(winners).toEqual({ '5': 'p1' });
  });

  it('survives a null/undefined stored map', () => {
    expect(mergeCtpWinners(
      null as never, { '5': 'p1' }, opts([5], ['p1']),
    ).winners).toEqual({ '5': 'p1' });
  });
});
