// ============================================================
// Parity ratchet — the Dart engines are the reference
// ============================================================
// W0 of the Flutter repo's docs/plans/WEBSITE_APP_PARITY_PLAN.md.
//
// WHY THIS FILE EXISTS. `src/lib` carries ~1,800 lines of TypeScript
// that re-implement the app's scoring math — leaderboard.ts says so in
// its own header: "Mirrors the Dart `LeaderboardBuilder.buildLeaderboard`
// … at a fraction of the complexity." Nothing tied the two together, so
// they were free to disagree about money and nobody would find out from
// a test. The only signal would have been a director noticing the
// website's leaderboard didn't match the app's.
//
// They already disagreed. `courseHandicap` here had no `holeCount`
// parameter and none of Dart's nine-hole guards, so every NINE-HOLE
// round computed a different handicap than the app. That is the same
// class of error that made Sam's Shattuck round of 2026-09-11 read net
// 3 (−40) for a 39 and needed migration 20261012 to repair. Team
// leagues are sixteen weeks of nine holes, so this was live.
//
// HOW IT WORKS. `__fixtures__/web-parity.json` is GENERATED by running
// the real Dart engines, by the Flutter repo's
// `test/parity/web_parity_fixtures_test.dart`. This test replays every
// case through the TypeScript and demands the same answer.
//
// WHEN THIS FAILS, the TypeScript is wrong until proven otherwise —
// Dart is the engine that ships in the app and settles real money.
//
// TO UPDATE after a deliberate Dart change:
//   1. (flutter repo) REGEN=1 flutter test test/parity/web_parity_fixtures_test.dart
//   2. verify the diff by hand
//   3. cp ../fairwayiq-flutter/test/parity/web_parity_fixtures.json \
//        src/lib/__fixtures__/web-parity.json
//   4. npm test — and fix the TypeScript if it now fails
//
// The two copies of the fixture must stay byte-identical. Nothing
// enforces that across repos, so step 3 is not optional.

import { describe, expect, it } from 'vitest';

import { courseHandicap, strokesOnHole } from './leaderboard';
import { allowanceAdjustedHandicap } from './handicapAllowance';
import {
  DIRECT_HANDICAP_COURSES,
  directCourseHandicap,
  usesDirectHandicap,
} from './directHandicap';
import fixtures from './__fixtures__/web-parity.json';

type CourseHandicapCase = {
  hi: number;
  slope: number;
  rating: number;
  par: number;
  holes: number;
  expected: number;
};

type StrokesCase = { ch: number; si: number; expected: number };

type AllowanceCase = { ch: number; allowance: number; expected: number };

const chCases = fixtures.courseHandicap as CourseHandicapCase[];
const strokesCases = fixtures.strokesOnHole as StrokesCase[];
const allowanceCases = fixtures.allowanceAdjustedHandicap as AllowanceCase[];
const directCourses = fixtures.directHandicapCourses as string[];

describe('courseHandicap matches the Dart engine', () => {
  for (const c of chCases) {
    const label =
      `hi=${c.hi} slope=${c.slope} rating=${c.rating} ` +
      `par=${c.par} holes=${c.holes} → ${c.expected}`;
    it(label, () => {
      expect(courseHandicap(c.hi, c.slope, c.rating, c.par, c.holes)).toBe(
        c.expected,
      );
    });
  }
});

describe('strokesOnHole matches the Dart engine', () => {
  for (const c of strokesCases) {
    it(`ch=${c.ch} si=${c.si} → ${c.expected}`, () => {
      expect(strokesOnHole(c.ch, c.si)).toBe(c.expected);
    });
  }
});

describe('allowanceAdjustedHandicap matches the Dart engine', () => {
  for (const c of allowanceCases) {
    it(`ch=${c.ch} allowance=${c.allowance} \u2192 ${c.expected}`, () => {
      expect(allowanceAdjustedHandicap(c.ch, c.allowance)).toBe(c.expected);
    });
  }
});

describe('the WHS opt-out course list matches the Dart catalog', () => {
  // This is the drift guard. `DIRECT_HANDICAP_COURSES` is hand-written
  // here because the website has no curated catalog; the fixture is
  // generated from Flutter's `kCuratedCourses`. Adding a fourth
  // opt-out course in the app fails THIS test until it is carried
  // across — which is the only thing stopping the Ballyneal class of
  // divergence from recurring on the next such course.
  it('has exactly the courses Dart marks useDirectHandicap', () => {
    expect([...DIRECT_HANDICAP_COURSES].sort()).toEqual([...directCourses].sort());
  });

  it('is not empty', () => {
    // An empty list on either side would make every assertion above
    // vacuously true while the website silently went back to WHS.
    expect(directCourses.length).toBeGreaterThan(0);
  });

  it('matches each catalog name case-insensitively, both directions', () => {
    for (const name of directCourses) {
      expect(usesDirectHandicap(name)).toBe(true);
      expect(usesDirectHandicap(name.toUpperCase())).toBe(true);
      expect(usesDirectHandicap(`  ${name}  `)).toBe(true);
    }
  });

  it('does not match an unrelated course', () => {
    expect(usesDirectHandicap('Shattuck Golf Club')).toBe(false);
    expect(usesDirectHandicap('Bandon Dunes')).toBe(false);
    expect(usesDirectHandicap('')).toBe(false);
    expect(usesDirectHandicap(null)).toBe(false);
    expect(usesDirectHandicap(undefined)).toBe(false);
  });

  it('rounds the index UP, toward zero for plus handicaps', () => {
    // Math.ceil matches Dart's num.ceil() on both signs.
    expect(directCourseHandicap(10.4)).toBe(11);
    expect(directCourseHandicap(11)).toBe(11);
    expect(directCourseHandicap(0)).toBe(0);
    expect(directCourseHandicap(-2.4)).toBe(-2);
  });
});

// A ratchet that quietly stops covering the thing it was built for
// passes forever. These assertions are about the FIXTURE, not the
// engines: if a future regeneration drops the nine-hole cases, the
// suite above would still be green while covering nothing that matters.
describe('the fixture still covers what it was built for', () => {
  it('carries both engines, non-empty', () => {
    expect(chCases.length).toBeGreaterThanOrEqual(15);
    expect(strokesCases.length).toBeGreaterThanOrEqual(50);
  });

  it('covers nine-hole rounds — the divergence this ratchet caught', () => {
    const nines = chCases.filter((c) => c.holes === 9);
    expect(nines.length).toBeGreaterThanOrEqual(4);
  });

  it('covers the Shattuck shape: an 18-hole rating on a nine', () => {
    // The worst case, and the one a naive port gets wrong: rating 73.0
    // against a nine-hole par. Without this case the fixture misses the
    // failure that cost a migration to repair.
    const shattuck = chCases.filter((c) => c.holes === 9 && c.rating > 50);
    expect(shattuck.length).toBeGreaterThanOrEqual(1);
  });

  it('covers a plus handicap, where JS and Dart rounding differ', () => {
    // Math.round(-0.5) is -0 in JS and -1 in Dart. A fixture with no
    // negative values would let that bug back in.
    expect(chCases.some((c) => c.hi < 0)).toBe(true);
  });

  it('covers plus handicaps in the allowance step', () => {
    // −5 at 0.85 must be −4, not −5. The website had three copies of
    // this function; a sign bug would have landed in all three.
    expect(allowanceCases.some((c) => c.ch < 0)).toBe(true);
    expect(allowanceCases.some((c) => c.allowance === 0.85)).toBe(true);
    expect(allowanceCases.some((c) => c.allowance === 1)).toBe(true);
    expect(allowanceCases.length).toBeGreaterThanOrEqual(40);
  });

  it('covers the multi-loop boundary in strokesOnHole', () => {
    // CH 18/19 is where a second stroke starts landing on low stroke
    // indexes. Off-by-one here changes who wins a skin.
    expect(strokesCases.some((c) => c.ch === 18)).toBe(true);
    expect(strokesCases.some((c) => c.ch === 19)).toBe(true);
    expect(strokesCases.some((c) => c.ch <= 0)).toBe(true);
  });
});
