import generated from './__generated__/formats.json';

/// The public round-format catalog — ONE list, merged from two halves.
///
/// FACTS (`__generated__/formats.json`) come from the app's
/// `RoundFormat` enum and `roundFormatMeta`, generated by
/// `test/parity/round_formats_catalog_test.dart` in fairwayiq-flutter.
/// Team size, whether a format is a team format, and whether it can be
/// one stretch of a segmented round are all decided there.
///
/// PROSE lives below. It is marketing copy, not configuration, so it
/// has no business in the app — the same split as `leagueCreate.ts`'s
/// BLURBS.
///
/// WHY THIS MODULE EXISTS. Until 2026-10-02 `/tournaments` hand-
/// maintained its own list of 12 formats while the app had 20, and
/// `buddies-trips.astro` linked to it as "See all tournament formats".
/// Two-Man Total shipped on 10-01 and never arrived. The same page
/// carried a SECOND list (`roundFormatLabels`) that was incomplete in
/// a different way. `roundFormats.test.ts` now fails if any format in
/// the generated file has no entry here, so the list cannot fall
/// behind silently again.

export interface RoundFormatFacts {
  code: string;
  label: string;
  teamSize: number;
  isTeamFormat: boolean;
  handicapAllowance: number | null;
  allowanceEngineOwned: boolean;
  v1Available: boolean;
  segmentable: boolean;
}

interface Prose {
  /// Display name for the catalog. Usually the app's label; occasionally
  /// expanded for a reader who has never heard the term.
  name: string;
  /// Short form for dense surfaces like the Cup round tables.
  shortName?: string;
  /// Roster shape, when it is not obvious from the team size alone.
  players?: string;
  body: string;
  /// Written out rather than computed from `handicapAllowance`,
  /// because the engine-owned ones are combination rules (50% of
  /// combined, 60/40, 25/20/15/10) that a single number cannot say.
  allowance?: string;
}

const PROSE: Record<string, Prose> = {
  stroke_play: {
    name: 'Stroke Play',
    shortName: 'Singles Stroke Play',
    body:
      'Each player records gross strokes per hole; the lowest 18-hole total wins. Net = gross minus course handicap. The World Handicap System caps any hole at net double bogey.',
    allowance: '95% Course Handicap',
  },
  match_play_singles: {
    name: 'Match Play (Singles)',
    shortName: 'Singles Match Play',
    body:
      '1-on-1 hole by hole. Win the hole = +1. The match ends when one side leads by more holes than remain (e.g. 4&3). Net match play applies 100% of the handicap difference on the lowest-index holes.',
  },
  stableford: {
    name: 'Stableford',
    body:
      'Points format: bogey=1, par=2, birdie=3, eagle=4, double-eagle=5; double-bogey or worse=0. Net Stableford applies handicap before scoring.',
    allowance: '95% Course Handicap',
  },
  modified_stableford: {
    name: 'Modified Stableford',
    body:
      'Stableford with a custom table that rewards aggressive play. PGA Tour Barracuda uses: eagle +5, birdie +2, par 0, bogey −1, double-or-worse −3.',
    allowance: '95% Course Handicap',
  },
  best_ball: {
    name: 'Best Ball / Four-Ball',
    shortName: 'Best Ball (Four-Ball)',
    players: '2-person teams',
    body:
      'Each player plays their own ball; the lower of the two team scores counts as the team hole score. Handicap applied BEFORE comparing (net per hole, not low gross). Common at member-guest events.',
    allowance: '85% Course Handicap (each player)',
  },
  best_ball_four_man: {
    name: 'Best Ball (4-Man, Best 2 of 4)',
    shortName: '4-Man Best Ball',
    players: '4-person teams',
    body:
      'Everyone plays their own ball; the team hole score is the sum of the two lowest nets in the group. Two bad balls are free, which keeps a big field moving and a weak player in the game.',
    allowance: '85% Course Handicap (each player)',
  },
  best_three_of_four: {
    name: 'Best Three of Four',
    players: '4-person teams',
    body:
      'Like Best 2 of 4 but kinder by one ball: drop only the highest net on each hole and add the other three. Forgiving enough for a mixed-ability foursome without letting anyone hide.',
    allowance: '100% Course Handicap (each player)',
  },
  two_man_total: {
    name: 'Two-Man Total',
    players: '2-person teams',
    body:
      'Also called Total Score of Partners. Both partners hole out and BOTH scores count on every hole — the team score is the sum. Nothing is thrown out, so one blow-up hole costs the team in full. The opposite temperament to Best Ball, where the worse ball simply disappears.',
    allowance: '100% Course Handicap (each player)',
  },
  twelves: {
    name: 'Twelves (2 v 2)',
    players: '2-person teams',
    body:
      'Combined net score of both partners on every hole — but only the best 12 of 18 holes count toward the team total. Six holes get thrown away, so a disaster is survivable and a hot stretch is decisive.',
    allowance: '100% Course Handicap (each player)',
  },
  high_low_2v2: {
    name: 'High-Low (2 v 2)',
    shortName: 'High-Low',
    players: '2-person teams',
    body:
      'Two points on the line every hole: the better net ball of each side plays the other for one, and the worse ball plays the other for one. Both partners stay in every hole, which is the point.',
    allowance: '100% Course Handicap (each player)',
  },
  scramble: {
    name: 'Scramble',
    players: '4-person default (2 and 3 supported)',
    body:
      'All teammates tee off; the captain picks the best drive; everyone plays their next shot from there until holed. One team gross per hole. Texas Scramble adds a minimum-drives rule (each player’s drive used at least 3 times) — organize manually.',
    allowance: '4 players: 25%A + 20%B + 15%C + 10%D (70% total)',
  },
  scramble_two_man: {
    name: '2-Man Scramble',
    players: '2-person teams',
    body:
      'The same pick-the-best-shot game with half the roster. Both partners play every shot from the chosen ball, so pace stays quick and a single good drive carries the hole.',
    allowance: '35% low + 15% high Course Handicap',
  },
  bramble: {
    name: 'Bramble / Shamble (2-man)',
    shortName: 'Bramble',
    players: '2-person teams',
    body:
      'Scramble off the tee, then your own ball to the hole. Everyone gets a drive they can play from and still has to finish it themselves — the most forgiving format that is still real golf.',
    allowance: '85% Course Handicap (each player)',
  },
  yellow_ball: {
    name: 'Yellow Ball (Devil Ball / Lone Ranger)',
    shortName: 'Yellow Ball',
    players: '4-person teams',
    body:
      'One designated ball rotates through the team hole by hole. The team score is that player’s net plus the best net of the other three — so everybody carries the group once a hole, in turn.',
    allowance: '90% Course Handicap (each player)',
  },
  foursomes: {
    name: 'Foursomes (Alternate Shot)',
    shortName: 'Foursomes (Alt Shot)',
    players: '2-person teams',
    body:
      'Partners alternate STROKES on a single ball. One partner tees off odd holes, the other even. Traditional, punishing, and gorgeous when it works.',
    allowance: '(low + high) × 50%',
  },
  greensomes: {
    name: 'Greensomes (Modified Alternate)',
    shortName: 'Greensomes',
    players: '2-person teams',
    body:
      'Both partners tee off; pick the better drive; the partner whose drive was NOT chosen plays the second. Alternate strokes from there.',
    allowance: '60% low + 40% high Course Handicap',
  },
  pinehurst: {
    name: 'Pinehurst (Chapman)',
    shortName: 'Pinehurst',
    players: '2-person teams',
    body:
      'Both partners tee off, then SWAP balls for the second shot. After the two seconds, pick one ball; the OTHER partner plays the third, and they alternate to the hole.',
    allowance: '60% low + 40% high',
  },
  bloodsome: {
    name: 'Bloodsome (Reverse Scramble)',
    players: '2-person teams',
    body:
      'Worst-drive variant of Foursomes. Both partners tee off; the captain picks the WORSE drive; the team plays alternate shot from there. Punishing but memorable.',
    allowance: '50% of combined Course Handicaps',
  },
  round_robin: {
    name: 'Round Robin',
    players: '4 players',
    body:
      'Partners rotate every 6 holes so every pairing plays together once. Holes 1–6: AB vs CD. 7–12: AC vs BD. 13–18: AD vs BC. Each 6-hole segment is its own match.',
    allowance: '100% Course Handicap',
  },
  six_six_six: {
    name: 'Six-Six-Six',
    players: '4 players',
    body:
      'Same rotation as Round Robin — three 6-hole segments — but best-ball scoring within each segment rather than match play. Note this rotates PARTNERS, not formats; for a round that changes format every six holes, see below.',
    allowance: '85% Course Handicap',
  },
};

export interface RoundFormatEntry extends RoundFormatFacts, Prose {
  kind: 'individual' | 'team';
}

const FACTS = generated.formats as RoundFormatFacts[];

/// Every format the app can run, in the app's own order.
///
/// Throws on a missing entry rather than skipping it. A silent skip is
/// how the list fell eight formats behind in the first place, and a
/// build that fails is cheaper than a page that lies.
export const ROUND_FORMATS: RoundFormatEntry[] = FACTS.map((f) => {
  const prose = PROSE[f.code];
  if (!prose) {
    throw new Error(
      `roundFormats.ts has no copy for "${f.code}" (${f.label}). ` +
        'A new format reached __generated__/formats.json without web copy. ' +
        'Add an entry to PROSE — see roundFormats.test.ts.',
    );
  }
  // `teamSize`, NOT `isTeamFormat`. The app's flag is narrower than a
  // reader's sense of the word: Round Robin, Six-Six-Six and
  // Bloodsome are all `isTeamFormat: false` because they do not use
  // the team-scoring surfaces, yet every one of them is played in
  // pairs. Deriving from the flag would have quietly moved three
  // partner formats into "Individual formats" on this page.
  return { ...f, ...prose, kind: f.teamSize > 1 ? 'team' : 'individual' };
});

/// Wire code → short display label, for dense surfaces like the Cup
/// round tables. Derived, so it cannot disagree with the catalog.
export const roundFormatLabels: Record<string, string> = Object.fromEntries(
  ROUND_FORMATS.map((f) => [f.code, f.shortName ?? f.name]),
);

/// Formats that can be ONE STRETCH of a round that changes format
/// partway (holes 1–6 alt-shot, 7–12 best ball, 13–18 two-man total).
export const SEGMENTABLE_FORMATS = ROUND_FORMATS.filter((f) => f.segmentable);

/// The number the app actually ships, for the "N side games" lines.
export const SIDE_GAME_COUNT: number = generated.sideGameCount;
export const ROUND_FORMAT_COUNT: number = generated.formatCount;
